version: '3.9'

services:
  petshop:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    networks:
      - microservices

  postgres:
    image: bitnami/postgresql
    container_name: postgres
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - microservices

networks:
  microservices:
    name: microservices